<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\METANOIA.Domain\METANOIA.Domain.csproj" />
    <ProjectReference Include="..\METANOIA.Application\METANOIA.Application.csproj" />
    <ProjectReference Include="..\METANOIA.Infrastructure\METANOIA.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
